# Generated by Django 4.1.6 on 2023-02-04 04:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_feature_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="script_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.script"
            ),
        ),
        migrations.AlterField(
            model_name="script",
            name="feature_hash",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
